### ISSUE TITLE
[QUESTION]: what is this-

### ISSUE THREAD

**Issue by kokonut27** [monjs-lib/monjs#3]
Wait, so what's the main concept for this project again?

> Sorry if this is the second time I asked-

**Comment by kokonut27** [comment]
@darkdarcool reply please (sorry for ping)

**Comment by darkdarcool** [comment]
Whoops sorry. It's just an assortment of utilities so developers don't have to write them on their own.

**Comment by kokonut27** [comment]
Oh okay, thanks
